### PR TITLE
GUide cleanup

### PR DESCRIPTION
**Pull request by taikedz**
Som initial cleanups.

I adjusted the images for now, but since they are all different sizes, I am going to eventually take new images in a standard size to add, and also clean up margins

Text: little by little correcting some grammar, spelling, wording etc. I was going to write another guide with my own text, but since the mobs are changing I will wait for the new version before I do that.

I'll also make a Markdown version of the guide, so that we can track changes better

### CODE REVIEW

**Comment by NPXcoot** [comment]
I still haven't accepted this PR only because we want to directly write the wiki page on the minetest wiki about the mod and we are waiting for the wiki account

**Comment by NPXcoot** [comment]
We are updating the wiki (if you want to help there you are welcome!) so I'm going to close this.

**Comment by taikedz** [comment]
Can';t seem to click through to the Wiki tab - or is this a wiki at a different location?

**Comment by NPXcoot** [comment]
The wiki on the minetest official wiki!;)
http://wiki.minetest.net/Mods/Not_So_Simple_Mobs

**Pull request closed without merging**
